export const STATE_CODE_BY_NAME: Record<string, string> = {
  'Andaman and Nicobar Islands': '35',
  'Andhra Pradesh': '28',
  'Arunachal Pradesh': '12',
  Assam: '18',
  Bihar: '10',
  Chandigarh: '04',
  Chhattisgarh: '22',
  'Dadra and Nagar Haveli and Daman and Diu': '26',
  Delhi: '07',
  Goa: '30',
  Gujarat: '24',
  Haryana: '06',
  'Himachal Pradesh': '02',
  'Jammu and Kashmir': '01',
  Jharkhand: '20',
  Karnataka: '29',
  Kerala: '32',
  Ladakh: '38',
  Lakshadweep: '31',
  'Madhya Pradesh': '23',
  Maharashtra: '27',
  Manipur: '14',
  Meghalaya: '17',
  Mizoram: '15',
  Nagaland: '13',
  Odisha: '21',
  Puducherry: '34',
  Punjab: '03',
  Rajasthan: '08',
  Sikkim: '11',
  'Tamil Nadu': '33',
  Telangana: '36',
  Tripura: '16',
  'Uttar Pradesh': '09',
  Uttarakhand: '05',
  'West Bengal': '19',
};

export const STATE_CODE_BY_ABBREVIATION: Record<string, string> = {
  AN: '35',
  AP: '28',
  AR: '12',
  AS: '18',
  BR: '10',
  CH: '04',
  CG: '22',
  DD: '26',
  DL: '07',
  GA: '30',
  GJ: '24',
  HR: '06',
  HP: '02',
  JK: '01',
  JH: '20',
  KA: '29',
  KL: '32',
  LA: '38',
  LD: '31',
  MP: '23',
  MH: '27',
  MN: '14',
  ML: '17',
  MZ: '15',
  NL: '13',
  OD: '21',
  OR: '21',
  PY: '34',
  PB: '03',
  RJ: '08',
  SK: '11',
  TN: '33',
  TS: '36',
  TG: '36',
  TR: '16',
  UP: '09',
  UK: '05',
  WB: '19',
};

export function getStateCode(stateName: string) {
  const cleaned = stateName.trim();
  if (!cleaned) return null;
  return STATE_CODE_BY_NAME[cleaned] ?? STATE_CODE_BY_ABBREVIATION[cleaned.toUpperCase()] ?? null;
}
