'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useSearchParams } from 'next/navigation'
import { AlertTriangle, Bell, BrainCircuit, Building2, CalendarDays, ChevronRight, CircleDollarSign, CreditCard, FileDown, FileText, Gauge, Landmark, LayoutDashboard, ListChecks, Search, ShieldCheck, SlidersHorizontal, Sparkles, TrendingUp } from 'lucide-react'
import { CreditIntelligence, formatCurrency, formatDate } from '@/lib/credit-intelligence/analytics'

type Payload = { intelligence: CreditIntelligence; history: Array<{ id: string; reportId: string; createdAt: string; score: number | null; accounts: number; currentBalance: number; overdueBalance: number }> }
type Section = 'dashboard' | 'report' | 'score' | 'accounts' | 'cards' | 'repayment' | 'dpd' | 'enquiries' | 'mix' | 'debt' | 'details' | 'negative' | 'compare' | 'insights' | 'plan' | 'alerts' | 'documents' | 'settings'

const nav: Array<{ id: Section; label: string; icon: typeof LayoutDashboard }> = [
  { id: 'dashboard', label: 'Overview', icon: LayoutDashboard }, { id: 'report', label: 'Credit Report', icon: FileText }, { id: 'score', label: 'Score Analysis', icon: Gauge }, { id: 'accounts', label: 'Loan Accounts', icon: Landmark }, { id: 'cards', label: 'Credit Cards', icon: CreditCard }, { id: 'repayment', label: 'Repayment History', icon: ListChecks }, { id: 'dpd', label: 'DPD Analysis', icon: CalendarDays }, { id: 'enquiries', label: 'Enquiries', icon: Search }, { id: 'mix', label: 'Credit Mix', icon: SlidersHorizontal }, { id: 'debt', label: 'Debt & Capacity', icon: CircleDollarSign }, { id: 'details', label: 'Account Details', icon: Building2 }, { id: 'negative', label: 'Negative Items', icon: AlertTriangle }, { id: 'compare', label: 'Compare Reports', icon: TrendingUp }, { id: 'insights', label: 'Smart Insights', icon: BrainCircuit }, { id: 'plan', label: 'Action Plan', icon: ListChecks }, { id: 'alerts', label: 'Alerts', icon: Bell }, { id: 'documents', label: 'Documents', icon: FileDown }, { id: 'settings', label: 'Settings', icon: SlidersHorizontal },
]

const toneClass = { positive: 'border-emerald-200 bg-emerald-50 text-emerald-700', warning: 'border-amber-200 bg-amber-50 text-amber-700', critical: 'border-rose-200 bg-rose-50 text-rose-700', info: 'border-blue-200 bg-blue-50 text-blue-700' }
const statusClass = (value: number | null) => value === null ? 'bg-slate-100 text-slate-600' : value >= 60 ? 'bg-rose-50 text-rose-700' : 'bg-emerald-50 text-emerald-700'

function Metric({ label, value, detail, icon: Icon, accent = 'blue' }: { label: string; value: string | number; detail: string; icon: typeof Gauge; accent?: 'blue' | 'green' | 'orange' | 'red' }) {
  const colors = { blue: 'bg-blue-50 text-blue-600', green: 'bg-emerald-50 text-emerald-600', orange: 'bg-amber-50 text-amber-600', red: 'bg-rose-50 text-rose-600' }
  return <div className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div><span className={`rounded-lg p-2 ${colors[accent]}`}><Icon size={19} /></span></div><p className="mt-2 text-sm text-slate-500">{detail}</p></div>
}

export default function CreditIntelligencePage() {
  const params = useSearchParams(); const requestId = params.get('request_id')
  const activeRequestId = requestId || 'shakti-demo'
  const [section, setSection] = useState<Section>('dashboard'); const [payload, setPayload] = useState<Payload | null>(null); const [error, setError] = useState(''); const [mobileMenu, setMobileMenu] = useState(false)
  useEffect(() => { setError(''); setPayload(null); fetch(`/api/customer-report/intelligence?request_id=${encodeURIComponent(activeRequestId)}`, { cache: 'no-store' }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to load your report'); setPayload(body) }).catch((reason) => setError(reason.message)) }, [activeRequestId])
  const data = payload?.intelligence
  const filteredAccounts = useMemo(() => !data ? [] : section === 'cards' ? data.accounts.filter((account) => account.category === 'credit_card') : data.accounts, [data, section])
  if (error) return <main className="grid min-h-screen place-items-center bg-slate-50 p-6"><div className="max-w-md rounded-lg border border-rose-200 bg-white p-7 text-center"><AlertTriangle className="mx-auto text-rose-600" /><h1 className="mt-4 text-xl font-bold">Unable to open this report</h1><p className="mt-2 text-sm text-slate-600">{error}</p><Link href="/get-my-report" className="mt-5 inline-flex rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Get my report</Link></div></main>
  if (!data) return <main className="grid min-h-screen place-items-center bg-slate-50"><div className="text-center"><div className="mx-auto h-10 w-10 animate-spin rounded-full border-4 border-blue-600 border-r-transparent" /><p className="mt-4 text-sm font-medium text-slate-600">Preparing your CreditTrust analysis...</p></div></main>
  const reportDownload = `/api/customer-report/download?request_id=${encodeURIComponent(activeRequestId)}`
  const isAccounts = section === 'accounts' || section === 'cards' || section === 'details'
  return <main className="min-h-screen bg-[#f7f9fc] text-slate-900"><aside className="fixed inset-y-0 left-0 z-30 hidden w-60 border-r border-slate-200 bg-white lg:block"><div className="border-b border-slate-100 px-6 py-6"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-blue-600 text-sm font-black text-white">CT</div><div><p className="font-bold tracking-tight text-slate-950">CreditTrust</p><p className="text-xs text-slate-500">Credit Intelligence</p></div></div></div><nav className="h-[calc(100vh-85px)] overflow-y-auto px-3 py-4">{nav.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setSection(id)} className={`mb-1 flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium ${section === id ? 'bg-blue-50 text-blue-700' : 'text-slate-600 hover:bg-slate-50'}`}><Icon size={17} />{label}{section === id && <ChevronRight className="ml-auto" size={15} />}</button>)}</nav></aside>
  <div className="lg:pl-60"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-slate-200 bg-white/95 px-4 backdrop-blur lg:px-8"><div className="flex items-center gap-3"><button onClick={() => setMobileMenu(!mobileMenu)} className="rounded-lg border border-slate-200 p-2 lg:hidden"><ListChecks size={18} /></button><div><p className="text-sm font-semibold text-slate-900">CreditTrust Verification</p><p className="text-xs text-slate-500">Report {data.reportId}</p></div></div><div className="flex items-center gap-2"><a href={reportDownload} className="inline-flex items-center gap-2 rounded-lg border border-blue-200 bg-white px-3 py-2 text-sm font-semibold text-blue-700"><FileDown size={16} /> <span className="hidden sm:inline">Download report</span></a><span className="grid h-8 w-8 place-items-center rounded-full bg-slate-900 text-xs font-bold text-white">{data.customerName.slice(0, 1).toUpperCase()}</span></div></header>
  {mobileMenu && <div className="fixed inset-x-4 top-20 z-40 max-h-[75vh] overflow-auto rounded-lg border border-slate-200 bg-white p-3 shadow-xl lg:hidden">{nav.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => { setSection(id); setMobileMenu(false) }} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm"><Icon size={16} />{label}</button>)}</div>}
  <div className="mx-auto max-w-[1550px] p-4 sm:p-6 lg:p-8"><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-blue-600">CREDIT INTELLIGENCE</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">{nav.find((item) => item.id === section)?.label}</h1><p className="mt-2 text-sm text-slate-500">Analysis for {data.customerName} · Updated {formatDate(data.generatedAt.slice(0, 10))}</p></div>{data.score && <div className="rounded-lg border border-blue-100 bg-blue-50 px-4 py-3"><p className="text-xs font-semibold uppercase text-blue-700">Credit score</p><p className="text-2xl font-bold text-blue-700">{data.score} <span className="text-sm font-medium">{data.scoreBand}</span></p></div>}</div>
  {section === 'dashboard' && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Credit score" value={data.score ?? 'N/A'} detail={data.score ? `${data.scoreBand} score band` : 'Not supplied in this report'} icon={Gauge} /><Metric label="Active accounts" value={data.totals.activeAccounts} detail={`${data.totals.accounts} total reported accounts`} icon={Landmark} accent="green" /><Metric label="Overdue balance" value={formatCurrency(data.totals.overdueBalance)} detail={data.totals.overdueBalance ? 'Needs attention' : 'No overdue in available summary'} icon={AlertTriangle} accent={data.totals.overdueBalance ? 'red' : 'green'} /><Metric label="Credit enquiries" value={data.totals.enquiries} detail={`${data.totals.recentEnquiries} in recent summary`} icon={Search} accent="orange" /></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_0.85fr]"><section className="rounded-lg border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Portfolio overview</h2><button onClick={() => setSection('accounts')} className="text-sm font-semibold text-blue-600">View accounts</button></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><div><p className="text-sm text-slate-500">Reported balance</p><p className="mt-1 text-xl font-bold">{formatCurrency(data.totals.currentBalance)}</p></div><div><p className="text-sm text-slate-500">High credit</p><p className="mt-1 text-xl font-bold">{formatCurrency(data.totals.highCredit)}</p></div><div><p className="text-sm text-slate-500">Available credit limit</p><p className="mt-1 text-xl font-bold">{data.totals.creditLimit ? formatCurrency(data.totals.creditLimit) : 'Not reported'}</p></div></div><div className="mt-6 border-t border-slate-100 pt-5"><p className="mb-3 text-sm font-semibold">Account composition</p><div className="flex h-3 overflow-hidden rounded-full bg-slate-100">{data.totals.accounts ? <><span className="bg-blue-600" style={{ width: `${(data.mix.secured / data.totals.accounts) * 100}%` }} /><span className="bg-cyan-500" style={{ width: `${(data.mix.unsecured / data.totals.accounts) * 100}%` }} /><span className="bg-violet-500" style={{ width: `${(data.mix.cards / data.totals.accounts) * 100}%` }} /></> : null}</div><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-600"><span>Secured: {data.mix.secured}</span><span>Unsecured: {data.mix.unsecured}</span><span>Cards: {data.mix.cards}</span><span>Overdrafts: {data.mix.overdrafts}</span></div></div></section><InsightPanel insights={data.insights} onOpen={() => setSection('insights')} /></div></>}
  {section === 'report' && <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><section className="rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">Report snapshot</h2><p className="mt-1 text-sm text-slate-500">Only data received in your bureau response is shown here.</p></div><dl className="grid grid-cols-1 divide-y divide-slate-100 sm:grid-cols-2 sm:divide-x sm:divide-y-0"><DataRow label="Name" value={data.customerName} /><DataRow label="Date of birth" value={formatDate(data.profile.dob)} /><DataRow label="PAN" value={data.profile.pan || 'Not available'} /><DataRow label="Mobile" value={data.profile.mobile || 'Not available'} /><DataRow label="Gender" value={data.profile.gender || 'Not available'} /><DataRow label="Reported addresses" value={String(data.profile.addresses)} /></dl></section><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-bold">Report details</h2><DataRow label="CreditTrust report reference" value={data.reportId} /><DataRow label="Generated" value={formatDate(data.generatedAt.slice(0, 10))} /><a href={reportDownload} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-3 text-sm font-semibold text-white"><FileDown size={16} /> Download financial report</a></section></div>}
  {section === 'score' && <section className="rounded-lg border border-slate-200 bg-white p-6"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><div className="grid h-36 w-36 shrink-0 place-items-center rounded-full border-[12px] border-blue-100"><div className="text-center"><p className="text-4xl font-bold text-blue-700">{data.score ?? '—'}</p><p className="text-xs font-semibold text-slate-500">{data.scoreBand}</p></div></div><div><h2 className="text-xl font-bold">Score analysis</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">This section shows the provider-supplied score and reason codes. CreditTrust does not calculate or promise a future score.</p>{data.reasonCodes.length ? <div className="mt-4 flex flex-wrap gap-2">{data.reasonCodes.map((code) => <span key={code} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700">Provider reason code: {code}</span>)}</div> : <p className="mt-4 text-sm text-slate-500">No score reason codes were supplied with this report.</p>}</div></div></section>}
  {isAccounts && <AccountTable accounts={filteredAccounts} title={section === 'cards' ? 'Credit cards' : section === 'details' ? 'All account details' : 'Loan accounts'} />}
  {section === 'repayment' && <section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-bold">Repayment history</h2><p className="mt-1 text-sm text-slate-500">DPD values are shown exactly from the payment-history string when supplied; source periods are not labelled where the bureau did not provide dates.</p><PaymentGrid accounts={data.accounts} /></section>}
  {section === 'dpd' && <><div className="grid gap-4 sm:grid-cols-3"><Metric label="Accounts with DPD" value={data.dpd.accountsWithDelays} detail="Non-zero markers found" icon={CalendarDays} accent={data.dpd.accountsWithDelays ? 'orange' : 'green'} /><Metric label="Delayed markers" value={data.dpd.delayedPayments} detail="Available payment-history records" icon={AlertTriangle} accent={data.dpd.delayedPayments ? 'orange' : 'green'} /><Metric label="Severe markers" value={data.dpd.severeDelays} detail="60+ DPD markers where supplied" icon={AlertTriangle} accent={data.dpd.severeDelays ? 'red' : 'green'} /></div><section className="mt-6 rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-bold">DPD trend</h2><PaymentGrid accounts={data.accounts} /></section></>}
  {section === 'enquiries' && <section className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">Credit enquiries</h2><p className="mt-1 text-sm text-slate-500">{data.enquiries.length ? 'Enquiries included in your report.' : 'No enquiry-level records were included in this report.'}</p></div>{data.enquiries.length ? <table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Lender</th><th className="px-5 py-3">Purpose</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Date</th></tr></thead><tbody>{data.enquiries.map((row, i) => <tr key={i} className="border-t border-slate-100"><td className="px-5 py-4 font-medium">{row.lender}</td><td className="px-5 py-4">{row.purpose}</td><td className="px-5 py-4">{row.amount ? formatCurrency(row.amount) : 'Not available'}</td><td className="px-5 py-4">{formatDate(row.date)}</td></tr>)}</tbody></table> : <Empty title="No enquiry data available" detail="This report did not include enquiry-level details." />}</section>}
  {section === 'mix' && <section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-bold">Credit mix</h2><p className="mt-1 text-sm text-slate-500">Based on account types supplied in the report.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Secured" value={data.mix.secured} detail="Asset-backed facilities" icon={ShieldCheck} accent="green" /><Metric label="Unsecured" value={data.mix.unsecured} detail="Personal / consumer credit" icon={Landmark} /><Metric label="Credit cards" value={data.mix.cards} detail="Revolving facilities" icon={CreditCard} accent="orange" /><Metric label="Overdrafts" value={data.mix.overdrafts} detail="Reported overdraft facilities" icon={CircleDollarSign} accent="red" /></div></section>}
  {section === 'debt' && <section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-bold">Debt & capacity</h2><p className="mt-1 text-sm text-slate-500">Income is not inferred from a credit report, so affordability or repayment capacity is not estimated here.</p><div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3"><Metric label="Current balance" value={formatCurrency(data.totals.currentBalance)} detail="Across account-level data" icon={CircleDollarSign} /><Metric label="Reported EMI" value={formatCurrency(data.accounts.reduce((sum, account) => sum + account.emi, 0))} detail="Only where source supplied EMI" icon={CalendarDays} accent="orange" /><Metric label="Overdue balance" value={formatCurrency(data.totals.overdueBalance)} detail="From bureau account summary" icon={AlertTriangle} accent={data.totals.overdueBalance ? 'red' : 'green'} /></div></section>}
  {section === 'negative' && <section className="rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">Negative items</h2><p className="mt-1 text-sm text-slate-500">Only explicit markers found in the bureau response are listed.</p></div>{data.negativeItems.length ? <div className="divide-y divide-slate-100">{data.negativeItems.map((item, i) => <div key={i} className="flex gap-3 p-5"><AlertTriangle className="mt-0.5 text-rose-600" size={18} /><div><p className="font-semibold">{item.issue}</p><p className="text-sm text-slate-500">{item.lender} · {item.account}</p></div></div>)}</div> : <Empty title="No negative account markers found" detail="No settlement, write-off, or legal marker was detected in the available account fields." />}</section>}
  {section === 'compare' && <section className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">Compare reports</h2><p className="mt-1 text-sm text-slate-500">A comparison is available only for reports generated with this same verified mobile number.</p></div>{payload.history.length > 1 ? <table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Report date</th><th className="px-5 py-3">Score</th><th className="px-5 py-3">Accounts</th><th className="px-5 py-3">Balance</th><th className="px-5 py-3">Overdue</th></tr></thead><tbody>{payload.history.map((row) => <tr key={row.id} className="border-t border-slate-100"><td className="px-5 py-4">{formatDate(row.createdAt.slice(0, 10))}</td><td className="px-5 py-4 font-semibold">{row.score ?? 'Not available'}</td><td className="px-5 py-4">{row.accounts}</td><td className="px-5 py-4">{formatCurrency(row.currentBalance)}</td><td className="px-5 py-4">{formatCurrency(row.overdueBalance)}</td></tr>)}</tbody></table> : <Empty title="No earlier saved report to compare" detail="Generate another report in the future with this mobile number to see changes here." />}</section>}
  {section === 'insights' && <section className="grid gap-4 lg:grid-cols-2">{data.insights.map((insight) => <div key={insight.id} className={`rounded-lg border p-5 ${toneClass[insight.tone]}`}><div className="flex items-center gap-3"><Sparkles size={19} /><h2 className="font-bold">{insight.title}</h2></div><p className="mt-3 text-sm leading-6">{insight.detail}</p></div>)}</section>}
  {section === 'plan' && <section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-bold">Suggested action plan</h2><p className="mt-1 text-sm text-slate-500">General education based on available report data, not lending or legal advice.</p><ol className="mt-6 space-y-4">{data.actionPlan.map((action, index) => <li key={action} className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-blue-600 text-sm font-bold text-white">{index + 1}</span><p className="pt-1 text-sm text-slate-700">{action}</p></li>)}</ol></section>}
  {section === 'alerts' && <section className="rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">Report alerts</h2><p className="mt-1 text-sm text-slate-500">Alerts reflect this report only. Continuous credit monitoring is not enabled.</p></div>{data.insights.length ? <div className="divide-y divide-slate-100">{data.insights.map((item) => <div key={item.id} className="flex items-start gap-3 p-5"><span className={`mt-0.5 h-2.5 w-2.5 rounded-full ${item.tone === 'critical' ? 'bg-rose-500' : item.tone === 'warning' ? 'bg-amber-500' : item.tone === 'positive' ? 'bg-emerald-500' : 'bg-blue-500'}`} /><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-slate-500">{item.detail}</p></div></div>)}</div> : <Empty title="No report alerts" detail="No source-derived alerts are available." />}</section>}
  {section === 'documents' && <section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-bold">Documents</h2><p className="mt-1 text-sm text-slate-500">Your downloaded document remains available during this secure report session.</p><div className="mt-5 flex items-center justify-between rounded-lg border border-slate-200 p-4"><div className="flex items-center gap-3"><span className="rounded-lg bg-rose-50 p-2 text-rose-600"><FileText size={20} /></span><div><p className="font-semibold">CreditTrust financial report</p><p className="text-sm text-slate-500">Reference {data.reportId}</p></div></div><a href={reportDownload} className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600"><FileDown size={16} /> Download</a></div></section>}
  {section === 'settings' && <section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-bold">Privacy & report access</h2><div className="mt-5 space-y-4 text-sm text-slate-600"><p>Your portal view is linked to your verified report session.</p><p>Account numbers and PAN are masked in this dashboard. Your full raw bureau data is retained securely only for the report service and authorised support processes.</p><a href="/privacy-policy" className="font-semibold text-blue-600">Read privacy policy</a></div></section>}
  </div></div></main>
}

function DataRow({ label, value }: { label: string; value: string }) { return <div className="p-5"><dt className="text-xs font-semibold uppercase text-slate-500">{label}</dt><dd className="mt-2 text-sm font-semibold text-slate-800">{value}</dd></div> }
function Empty({ title, detail }: { title: string; detail: string }) { return <div className="p-10 text-center"><ShieldCheck className="mx-auto text-slate-300" size={32} /><p className="mt-3 font-semibold">{title}</p><p className="mx-auto mt-2 max-w-md text-sm text-slate-500">{detail}</p></div> }
function InsightPanel({ insights, onOpen }: { insights: CreditIntelligence['insights']; onOpen: () => void }) { return <section className="rounded-lg border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Key insights</h2><button onClick={onOpen} className="text-sm font-semibold text-blue-600">View all</button></div><div className="mt-4 space-y-3">{insights.slice(0, 4).map((item) => <div key={item.id} className={`rounded-lg border px-3 py-3 ${toneClass[item.tone]}`}><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs leading-5">{item.detail}</p></div>)}</div></section> }
function AccountTable({ accounts, title }: { accounts: CreditIntelligence['accounts']; title: string }) { return <section className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">Masked account data from the bureau response.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{accounts.length} accounts</span></div>{accounts.length ? <div className="overflow-x-auto"><table className="min-w-[860px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Lender</th><th className="px-5 py-3">Product</th><th className="px-5 py-3">Opened</th><th className="px-5 py-3">Current balance</th><th className="px-5 py-3">Overdue</th><th className="px-5 py-3">Utilisation</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{accounts.map((account) => <tr key={account.id} className="border-t border-slate-100"><td className="px-5 py-4"><p className="font-semibold">{account.lender}</p><p className="text-xs text-slate-500">{account.accountNumber}</p></td><td className="px-5 py-4">{account.product}</td><td className="px-5 py-4">{formatDate(account.openedAt)}</td><td className="px-5 py-4">{formatCurrency(account.currentBalance)}</td><td className="px-5 py-4">{formatCurrency(account.overdue)}</td><td className="px-5 py-4">{account.utilization === null ? 'Not reported' : <span className={`rounded-full px-2 py-1 text-xs font-semibold ${statusClass(account.utilization)}`}>{account.utilization}%</span>}</td><td className="px-5 py-4 capitalize">{account.status}</td></tr>)}</tbody></table></div> : <Empty title="No account data available" detail="This report did not include account-level information for this section." />}</section> }
function PaymentGrid({ accounts }: { accounts: CreditIntelligence['accounts'] }) { const withHistory = accounts.filter((account) => account.paymentHistory.length); return withHistory.length ? <div className="mt-5 space-y-5">{withHistory.map((account) => <div key={account.id}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{account.lender} · {account.accountNumber}</span><span className="text-slate-500">{account.product}</span></div><div className="flex flex-wrap gap-1.5">{account.paymentHistory.slice(-24).map((dpd, index) => <span key={`${dpd}-${index}`} title={`DPD: ${dpd}`} className={`min-w-9 rounded px-2 py-1 text-center text-xs font-bold ${dpd === '000' ? 'bg-emerald-100 text-emerald-700' : /^0?[1-5]\d?$/.test(dpd) ? 'bg-amber-100 text-amber-700' : /^\d/.test(dpd) ? 'bg-rose-100 text-rose-700' : 'bg-slate-100 text-slate-500'}`}>{dpd}</span>)}</div></div>)}</div> : <Empty title="No DPD history supplied" detail="The bureau response did not include payment-history strings for the reported accounts." /> }
